# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

# serverless.yml

service: serverless-nodejs-app

custom: # add these two lines
  defaultStage: dev
  secrets: ${file(secrets.json)} # reference the secrets.json file
  envVars: ${file(secrets.json):${opt:stage, self:custom.defaultStage}}

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, self:custom.defaultStage} # make sure to change this to production
  region: eu-central-1
  environment: # add environment property
    KEY: ${self:custom.envVars.key}
    # reference the KEY from the secrets.json file
    ####### Here you can Add more enviroment varibles ########

functions:
  app:
    handler: app.server
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true